openapi: 3.2.0
info:
  title: User Management Service Trial API
  version: 1.0.0
servers:
- url: /airmdrapi
tags:
- name: Trial
paths:
  /trial/register:
    post:
      tags:
      - Trial
      operationId: registerTrialAPI
      summary: register trial
      description: Registers a trial account.
      parameters:
      - name: User-ID
        in: header
        description: The User ID of the requestor. If requests are made through API Gateway, this header will be pre filled.
        schema:
          type: string
      - name: Organization-ID
        in: header
        description: The Organization ID of the requestor. If requests are made through API Gateway, this header will be pre filled.
        schema:
          type: string
      - name: X-Request-ID
        in: header
        description: The ID associated with the request. If requests are made through API Gateway, this header will be pre filled.
        schema:
          type: string
      security:
      - SessionCookie: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterTrialRequest'
      responses:
        '200':
          description: trial registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterTrialResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    TrialFeature:
      type: string
      enum:
      - alert_catalog
      x-enum-varnames:
      - TrialFeatureAlertCatalog
    Error:
      type: object
      required:
      - message
      properties:
        message:
          type: string
          description: user friendly error message
    RegisterTrialResponse:
      type: object
      required:
      - message
      - data
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            trail_link:
              type: string
    RegisterTrialRequest:
      type: object
      required:
      - email
      - trail_feature
      properties:
        email:
          type: string
        trail_feature:
          $ref: '#/components/schemas/TrialFeature'
  securitySchemes:
    SessionCookie:
      type: apiKey
      in: cookie
      name: Session
x-tagGroups:
- name: Included APIs
  tags:
  - Organization
  - User
  - User Group
  - Token
  - Permission
