openapi: 3.2.0
info:
  title: Case Manager Mitre Tactics API
  version: 1.0.0
servers:
- url: /airmdrapi
tags:
- name: MitreTactics
paths:
  /mitre_tactics:
    get:
      tags:
      - MitreTactics
      operationId: listMitreTacticsAPI
      summary: Get the list of Mitre tactics
      parameters:
      - name: X-Request-ID
        in: header
        description: The ID associated with the request
        schema:
          type: string
      - name: Organization-ID
        in: header
        description: The Organization ID of the requestor. If requests are made through API Gateway, this header will be pre filled.
        schema:
          type: string
      - name: User-ID
        in: header
        description: The User ID of the requestor. If requests are made through API Gateway, this header will be pre filled.
        schema:
          type: string
      - name: page
        in: query
        description: The page number
        schema:
          type: integer
      - name: size
        in: query
        description: The number of results per page
        schema:
          type: integer
      security:
      - SessionCookie: []
      responses:
        '200':
          description: List of Mitre tactics fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListMitreTacticsResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
      - MitreTactics
      operationId: addMitreTacticsAPI
      summary: Add a Mitre tactic
      parameters:
      - name: X-Request-ID
        in: header
        description: The ID associated with the request
        schema:
          type: string
      - name: Organization-ID
        in: header
        description: The Organization ID of the requestor. If requests are made through API Gateway, this header will be pre filled.
        schema:
          type: string
      - name: User-ID
        in: header
        description: The User ID of the requestor. If requests are made through API Gateway, this header will be pre filled.
        schema:
          type: string
      requestBody:
        description: The Mitre tactic to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMitreTacticsRequest'
      security:
      - SessionCookie: []
      responses:
        '200':
          description: Mitre tactic added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddMitreTacticsResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    AddMitreTacticsRequest:
      type: object
      required:
      - mitre_tactics
      properties:
        mitre_tactics:
          type: array
          items:
            type: string
    Error:
      type: object
      required:
      - message
      properties:
        message:
          type: string
          description: user friendly error message
    ListMitreTacticsResponse:
      type: object
      required:
      - data
      - total
      - message
      properties:
        data:
          type: array
          items:
            type: string
        total:
          type: integer
        message:
          type: string
    AddMitreTacticsResponse:
      type: object
      required:
      - message
      - data
      properties:
        message:
          type: string
        data:
          type: array
          items:
            type: string
  securitySchemes:
    SessionCookie:
      type: apiKey
      in: cookie
      name: Session
x-tagGroups:
- name: Included APIs
  tags:
  - Case Manager V2
  - Dashboard
  - Alerts
  - Webhooks
  - Query DSL
